version: '3.9'
services:
  kev-loader:
    build: ./kev-loader
    volumes:
      - ./kev-loader:/app
    depends_on:
      - db
    environment:
      - DB_HOST=ogotodb
      - DB_USER=ogoto
      - DB_PASS=hashmap

  db:
    image: mysql:8
    container_name: ogoto-db
    restart: always
    environment:
        MYSQL_DATABASE: 'ogoto'
        MYSQL_USER: 'ogoto'
        MYSQL_PASSWORD: 'hashmap'
        MYSQL_ROOT_PASSWORD: 'threeblindmice'
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d:ro
      - /opt/apps/ogotodb:/var/lib/mysql
    ports:
      - "3306:3306"

